### ISSUE TITLE
use a symbol for HTML details

### ISSUE THREAD

**Issue by apreshill** [rich-iannone/edr#10]
It should have been more obvious to me, but I wonder if we could use a symbol for the details "code hints". I didn't realize you could click on those. I think the default right arrow that rotates on click is nice, like here:

https://sass-lang.com/documentation/at-rules/extend

**Comment by rich-iannone** [comment]
This is an area ripe for innovation/experimentation. A more prominent symbol (maybe without the disclosure triangle) would be better. Also, that you can press this and get details is not explained anywhere in the text. Another also: is this accessible?

**Comment by apreshill** [comment]
Related article: https://www.hassellinclusion.com/blog/accessible-accordions-part-2-using-details-summary/
